# Start the testnet server with the command 'docker-compose up -d'

mongo-jwt-auth:
  image: mongo:4.2-bionic
  container_name: mongo-jwt-auth
  ports:
    - "172.17.0.1:5555:27017" # <host port>:<container port>
  volumes:
    - ./database:/data/db
  command: mongod --logpath=/dev/null # -- quiet
  restart: always

jwt-auth-api:
  build: ./production/
  dockerfile: Dockerfile
  container_name: jwt-auth-api
  links:
    - mongo-jwt-auth
  ports:
    - "5001:5001"  # <host port>:<container port>
  volumes:
    - ./logs:/home/safeuser/jwt-bch-api/logs
    - ./config:/home/safeuser/jwt-bch-api/config
  restart: always
